[package]
name = "httpet"
description = "Code for httpet.org"
version = "0.0.2"
edition = "2024"

default-run = "httpet"

[dependencies]
anyhow = "1.0.102"
askama = "0.16.0"
askama_web = { version = "0.16.0", features = ["axum-0.8"] }
axum = { version = "0.8.9", features = ["macros", "multipart"] }
clap = { version = "4.6.1", features = ["derive", "env"] }
chrono = "0.4.45"
sea-orm = "2.0.0"
sea-orm-migration = { version = "2.0.0", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
], default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
simple_logger = "5.2.0"
tokio = { version = "1.52.3", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "time",
    "tracing",
    "signal",
] }
tracing = { version = "0.1.44", features = ["log", "release_max_level_debug"] }
tower-http = { version = "0.7.0", features = ["fs"] }
tower-sessions = "0.15.0"
rand = "0.10.1"
url = "2.5.8"
serde_json = "1.0.150"
html-escape = "0.2.13"
httpdate = "1.0.3"
regex = "1.12.3"
ureq = "3.3.0"
time = "0.3.47"
image = { version = "0.25.10", default-features = false, features = [
    "jpeg",
    "png",
] }
reqwest = { version = "0.13.4", features = ["json"] }
base64 = "0.23.0"

[dev-dependencies]
http-body-util = "0.1.2"
tempfile = "3.27.0"
tower = "0.5.2"
