[tasks.check]
description = "Run rust checks"
depends = ['clippy', 'fmt', 'test']

[tasks.fmt]
description = "Check rust code formatting"
run = [
    # running cargo fmt --check then running it to just fix things
    "cargo fmt --all --check || true",
    "cargo fmt --all",
]

[tasks.test]
description = "Run rust tests"
run = "cargo test --quiet"

[tasks.clippy]
description = "Run an aggressive clippy"
run = "cargo clippy --all-targets --all-features --quiet"

[tasks.semgrep]
description = "Run semgrep"
run = "just semgrep"

[tasks.biome]
run = ["biome check static/*.css", "biome check templates/*.html"]
description = "Run biome lint"

[tools]
biome = "latest"
semgrep = "latest"
